# Generated by Django 2.0.2 on 2019-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('track_thumbnail', models.ImageField(upload_to='media/images/Music')),
                ('track_file', models.FileField(upload_to='media/tracks')),
            ],
        ),
    ]
