# Generated by Django 2.0.2 on 2019-10-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='track_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
