# Generated by Django 2.0.2 on 2019-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_track_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='track_file',
        ),
    ]
