# Generated by Django 2.0.2 on 2019-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=350)),
                ('blog_post', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('blog_image', models.ImageField(upload_to='media/images/blog')),
            ],
        ),
    ]
